export const fakeData = [
    {
        id: '1',
        firstName: 'Dylan',
        lastName: 'Murray',
        city: 'East Daphne',
        state: 'Kentucky',
        managerId: null,
    },
    {
        id: '2',
        firstName: 'Raquel',
        lastName: 'Kohler',
        city: 'Columbus',
        state: 'Ohio',
        managerId: null,
    },
    {
        id: '3',
        firstName: 'Jordon',
        lastName: 'Harris',
        city: 'Perth',
        state: 'Western Australia',
        managerId: null,
    },
];

//50 us states array
export const usStates = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Puerto Rico',
    'Western Australia',
    'Northern Territory',
    'South Australia',
    'Queensland',
];